"""hotel_d added in conversation

Revision ID: 0148fa9f6dfe
Revises: 41d09c106d33
Create Date: 2026-05-25 18:33:10.309499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0148fa9f6dfe'
down_revision = '41d09c106d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hotel_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'hotels', ['hotel_id'], ['id'])

    with op.batch_alter_table('user_cred', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_cred', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('hotel_id')

    # ### end Alembic commands ###
