"""Added date,person columns into bookings and transaction

Revision ID: 0e76fd3719e1
Revises: 28f9ce9dc09c
Create Date: 2026-04-15 10:39:27.819818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e76fd3719e1'
down_revision = '28f9ce9dc09c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_adult', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('no_child', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('date')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('date')
        batch_op.drop_column('status')
        batch_op.drop_column('no_child')
        batch_op.drop_column('no_adult')

    # ### end Alembic commands ###
