"""Added no rooms column in hotel, romms table

Revision ID: 28f9ce9dc09c
Revises: c607fd5986b0
Create Date: 2026-04-15 10:19:47.551299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f9ce9dc09c'
down_revision = 'c607fd5986b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_rooms', sa.Integer(), nullable=False))

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_rooms', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('available_rooms', sa.Integer(), nullable=False))
        batch_op.drop_column('status')
        batch_op.drop_column('available_no_rooms')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_no_rooms', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_column('available_rooms')
        batch_op.drop_column('no_rooms')

    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.drop_column('total_rooms')

    # ### end Alembic commands ###
