"""removed availableRoom column in rooms

Revision ID: 2b8d90e61587
Revises: bd52084134c8
Create Date: 2026-05-04 11:36:40.318398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b8d90e61587'
down_revision = 'bd52084134c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('available_rooms')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_rooms', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
