"""removed total_rooms from hotels

Revision ID: 41d09c106d33
Revises: 838b2aebaf0d
Create Date: 2026-05-18 12:09:45.406604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41d09c106d33'
down_revision = '838b2aebaf0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.drop_column('total_rooms')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_rooms', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
