"""changes in booking table

Revision ID: 422e390ffd61
Revises: 0e76fd3719e1
Create Date: 2026-04-29 14:13:13.099656

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '422e390ffd61'
down_revision = '0e76fd3719e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nights', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('person', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('booking_date', sa.DateTime(), nullable=False))
        batch_op.drop_column('no_adult')
        batch_op.drop_column('date')
        batch_op.drop_column('no_child')

    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.alter_column('images',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'default_hotel.avif'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.alter_column('images',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'default_hotel.avif'::character varying"))

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_child', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('no_adult', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('booking_date')
        batch_op.drop_column('person')
        batch_op.drop_column('nights')

    # ### end Alembic commands ###
