"""column name chenged in booking

Revision ID: 6764cb97c93b
Revises: c4c6f647a169
Create Date: 2026-04-29 16:40:35.103994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6764cb97c93b'
down_revision = 'c4c6f647a169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('no_rooms', new_column_name='bedrooms')
     

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('bedrooms', new_column_name='no_rooms')

    # ### end Alembic commands ###
