"""removed foreign key contstraints from user_id and host_id in conversation

Revision ID: 67bffef4240d
Revises: 0148fa9f6dfe
Create Date: 2026-05-26 10:25:08.016894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67bffef4240d'
down_revision = '0148fa9f6dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('conversation_host_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('conversation_user_id_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('conversation_user_id_fkey'), 'user_cred', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('conversation_host_id_fkey'), 'user_cred', ['host_id'], ['id'])

    # ### end Alembic commands ###
