"""online and lastSeen added in user table

Revision ID: 704cabb05a29
Revises: 67bffef4240d
Create Date: 2026-05-28 12:30:44.410723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704cabb05a29'
down_revision = '67bffef4240d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user_cred', ['user_id'], ['id'])

    with op.batch_alter_table('user_cred', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_online', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_cred', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('last_seen')
        batch_op.drop_column('is_online')

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
