"""removed active and approve column in hotels

Revision ID: 838b2aebaf0d
Revises: c711df77b44a
Create Date: 2026-05-05 11:11:28.654263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '838b2aebaf0d'
down_revision = 'c711df77b44a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
