"""cancellation column added in bookings

Revision ID: bd52084134c8
Revises: 39c28d1ac2be
Create Date: 2026-05-01 11:28:53.596346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd52084134c8'
down_revision = '39c28d1ac2be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancel_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_by', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('cancelled_by')
        batch_op.drop_column('cancel_reason')

    # ### end Alembic commands ###
