"""added cascade deletion in rooms and room_image

Revision ID: f1471b635f47
Revises: 704cabb05a29
Create Date: 2026-06-15 11:44:18.422077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1471b635f47'
down_revision = '704cabb05a29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room__image', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('room__image_room_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'rooms', ['room_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room__image', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('room__image_room_id_fkey'), 'rooms', ['room_id'], ['id'])

    # ### end Alembic commands ###
